name: Nix Seed
description: Build and push Nix Seed environments to GHCR

inputs:
  nix_conf:
    description: Extra nix.conf entries
  github_token:
    description: GitHub Token for GHCR Publish
  tags:
    description: Extra tags (space-separated)
  tag_latest:
    description: Apply the latest tag (use only when tagging the manifest)
    default: "false"
  registry:
    description: Container registry (default ghcr.io)
    default: ghcr.io
  cachix_name:
    description: Cachix cache name
    default: ${{ github.event.repository.name }}
  cachix_token:
    description: Cachix auth token
  seed_attr:
    description: Flake package attribute of the build seed
    default: .#seed

runs:
  using: composite
  steps:
    - name: Nix Setup
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          ${{ inputs.nix_conf }}
        cachix_name: ${{ inputs.cachix_name }}
        cachix_auth_token: ${{ inputs.cachix_token }}

    - name: Build seed
      shell: bash
      run: |
        set -euo pipefail
        nix build "${{ inputs.seed_attr }}"

    - name: GHCR Publish
      if: ${{ inputs.github_token != '' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
        set -euo pipefail
        image_ref=$(docker load < result | sed -n 's/^Loaded image: //p')
        name=${{ inputs.registry }}/${{ github.repository }}
        docker tag "$image_ref" "$name:${{ github.sha }}"
        tags="$(git describe --tags --always) ${{ inputs.tags }}"
        if [ "${{ inputs.tag_latest }}" = "true" ]; then
          tags="$tags latest"
        fi
        for tag in $tags; do
          [ -z "$tag" ] && continue
          docker tag "$image_ref" "$name:$tag"
        done
        echo "$GITHUB_TOKEN" \
          | docker login ghcr.io \
              --username ${{ github.actor }} \
              --password-stdin
        docker push --all-tags "$name"
