name: build-project
on: [push]
permissions:
  contents: read
  packages: write
jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project seed
        run: |
          nix build .#seed
      - name: Export attestation
        run: |
          mkdir -p attestations
          cp result/attestation.json attestations/project.json
      - name: Verify and attach
        run: |
          ./bin/verify \
            ghcr.io/${{ github.repository }}:${{ github.sha }} \
            -d attestations \
            -r 2 \
            -A \
            -a
